### ISSUE TITLE
How to use with cache

### ISSUE THREAD

**Issue by patrickkusebauch** [orklah/psalm-use-constants#1]
Hi,
I was wondering, how can I use this plugin with cache? I understand you might need it, but...

It is not possible for me to run psalm without cache every single time. And I don't see any way to conditionally disable the plugin and hence run it only from time to time. Any advice?

**Comment by orklah** [comment]
Hey! The reason for the --no-cache requirement is that one of the hook I use for this plugin is not called when the cache is already built, so this plugin won't be useful that way (it won't be able to create a list of every constant to compare to your literals)

I don't mind if you propose a PR to only output a warning instead of die() so you can run your usual analysis. However, be warned that this plugin doesn't output issues (yet?). It is made to fix the code automatically so I'm not sure it's something you want to run alongside your CI

**Comment by patrickkusebauch** [comment]
Thanks for the quick response. Is it correct that this is more a [Psalter](https://psalm.dev/docs/manipulating_code/fixing/) tool, more than a tool for normal Psalm static analysis?

**Comment by orklah** [comment]
Yeah, for now it totally is. This will have no impact on a standard analysis.

I may start to emit issues in the future, but I will have some tests to do and maybe find a complete other way to tackle this (because of the cache issue).

If you're interested and want to dig a little, I'd be happy to accept PRs :)

**Comment by orklah** [comment]
btw, if you're interested by this sort of things, feel free to check my other plugins :) https://github.com/orklah/orklah

I have some that fixes code and some that emit issues (and some that do both!)
